services:
  combo_176_l1:
    container_name: combo_176_l1_fastly-simulation
    depends_on:
    - combo_176_l2
    image: nginx:1.25
    ports:
    - 8175:80
    restart: unless-stopped
  combo_176_l2:
    container_name: combo_176_l2_envoy_1.29
    depends_on:
    - combo_176_l3
    image: envoyproxy/envoy:v1.29-latest
    ports:
    - 9175:80
    restart: unless-stopped
  combo_176_l3:
    container_name: combo_176_l3_lighttpd_1.4.71
    image: sebp/lighttpd:1.4.71
    ports:
    - 10175:80
    restart: unless-stopped
version: '3.8'
