services:
  combo_020_l1:
    container_name: combo_020_l1_cloudflare-simulation
    depends_on:
    - combo_020_l2
    image: nginx:alpine
    ports:
    - 8019:80
    restart: unless-stopped
  combo_020_l2:
    container_name: combo_020_l2_varnish_7.5
    depends_on:
    - combo_020_l3
    image: varnish:7.5
    ports:
    - 9019:80
    restart: unless-stopped
  combo_020_l3:
    container_name: combo_020_l3_lighttpd_1.4.72
    image: sebp/lighttpd:1.4.72
    ports:
    - 10019:80
    restart: unless-stopped
version: '3.8'
