services:
  combo_098_l1:
    container_name: combo_098_l1_akamai-simulation
    depends_on:
    - combo_098_l2
    image: nginx:1.24
    ports:
    - 8097:80
    restart: unless-stopped
  combo_098_l2:
    container_name: combo_098_l2_traefik_3.1
    depends_on:
    - combo_098_l3
    image: traefik:3.1
    ports:
    - 9097:80
    restart: unless-stopped
  combo_098_l3:
    container_name: combo_098_l3_apache_2.4.58
    image: httpd:2.4.58
    ports:
    - 10097:80
    restart: unless-stopped
version: '3.8'
