services:
  combo_189_l1:
    container_name: combo_189_l1_cloudflare-simulation
    depends_on:
    - combo_189_l2
    image: nginx:alpine
    ports:
    - 8188:80
    restart: unless-stopped
  combo_189_l2:
    container_name: combo_189_l2_haproxy_3.0
    depends_on:
    - combo_189_l3
    image: haproxy:3.0
    ports:
    - 9188:80
    restart: unless-stopped
  combo_189_l3:
    container_name: combo_189_l3_tomcat_9.0
    image: tomcat:9.0
    ports:
    - 10188:80
    restart: unless-stopped
version: '3.8'
