services:
  combo_075_l1:
    container_name: combo_075_l1_akamai-simulation
    depends_on:
    - combo_075_l2
    image: nginx:1.24
    ports:
    - 8074:80
    restart: unless-stopped
  combo_075_l2:
    container_name: combo_075_l2_varnish_7.4
    depends_on:
    - combo_075_l3
    image: varnish:7.4
    ports:
    - 9074:80
    restart: unless-stopped
  combo_075_l3:
    container_name: combo_075_l3_tomcat_10.1
    image: tomcat:10.1
    ports:
    - 10074:80
    restart: unless-stopped
version: '3.8'
