services:
  combo_133_l1:
    container_name: combo_133_l1_fastly-simulation
    depends_on:
    - combo_133_l2
    image: nginx:1.25
    ports:
    - 8132:80
    restart: unless-stopped
  combo_133_l2:
    container_name: combo_133_l2_varnish_7.4
    depends_on:
    - combo_133_l3
    image: varnish:7.4
    ports:
    - 9132:80
    restart: unless-stopped
  combo_133_l3:
    container_name: combo_133_l3_apache_2.4.58
    image: httpd:2.4.58
    ports:
    - 10132:80
    restart: unless-stopped
version: '3.8'
