services:
  combo_013_l1:
    container_name: combo_013_l1_cloudflare-simulation
    depends_on:
    - combo_013_l2
    image: nginx:alpine
    ports:
    - 8012:80
    restart: unless-stopped
  combo_013_l2:
    container_name: combo_013_l2_varnish_7.5
    depends_on:
    - combo_013_l3
    image: varnish:7.5
    ports:
    - 9012:80
    restart: unless-stopped
  combo_013_l3:
    container_name: combo_013_l3_apache_2.4.57
    image: httpd:2.4.57
    ports:
    - 10012:80
    restart: unless-stopped
version: '3.8'
