services:
  combo_270_l1:
    container_name: combo_270_l1_fastly-simulation
    depends_on:
    - combo_270_l2
    image: nginx:1.25
    ports:
    - 8269:80
    restart: unless-stopped
  combo_270_l2:
    container_name: combo_270_l2_traefik_3.1
    depends_on:
    - combo_270_l3
    image: traefik:3.1
    ports:
    - 9269:80
    restart: unless-stopped
  combo_270_l3:
    container_name: combo_270_l3_openlitespeed_1.7
    image: litespeedtech/openlitespeed:1.7
    ports:
    - 10269:80
    restart: unless-stopped
version: '3.8'
