services:
  combo_053_l1:
    container_name: combo_053_l1_cloudflare-simulation
    depends_on:
    - combo_053_l2
    image: nginx:alpine
    ports:
    - 8052:80
    restart: unless-stopped
  combo_053_l2:
    container_name: combo_053_l2_envoy_1.29
    depends_on:
    - combo_053_l3
    image: envoyproxy/envoy:v1.29-latest
    ports:
    - 9052:80
    restart: unless-stopped
  combo_053_l3:
    container_name: combo_053_l3_nginx_1.26
    image: nginx:1.26
    ports:
    - 10052:80
    restart: unless-stopped
version: '3.8'
