services:
  combo_016_l1:
    container_name: combo_016_l1_cloudflare-simulation
    depends_on:
    - combo_016_l2
    image: nginx:alpine
    ports:
    - 8015:80
    restart: unless-stopped
  combo_016_l2:
    container_name: combo_016_l2_varnish_7.3
    depends_on:
    - combo_016_l3
    image: varnish:7.3
    ports:
    - 9015:80
    restart: unless-stopped
  combo_016_l3:
    container_name: combo_016_l3_tomcat_10.1
    image: tomcat:10.1
    ports:
    - 10015:80
    restart: unless-stopped
version: '3.8'
