services:
  combo_035_l1:
    container_name: combo_035_l1_cloudflare-simulation
    depends_on:
    - combo_035_l2
    image: nginx:alpine
    ports:
    - 8034:80
    restart: unless-stopped
  combo_035_l2:
    container_name: combo_035_l2_haproxy_2.8
    depends_on:
    - combo_035_l3
    image: haproxy:2.8
    ports:
    - 9034:80
    restart: unless-stopped
  combo_035_l3:
    container_name: combo_035_l3_openlitespeed_1.8
    image: litespeedtech/openlitespeed:1.8
    ports:
    - 10034:80
    restart: unless-stopped
version: '3.8'
