services:
  combo_181_l1:
    container_name: combo_181_l1_cloudflare-simulation
    depends_on:
    - combo_181_l2
    image: nginx:alpine
    ports:
    - 8180:80
    restart: unless-stopped
  combo_181_l2:
    container_name: combo_181_l2_envoy_1.28
    depends_on:
    - combo_181_l3
    image: envoyproxy/envoy:v1.28-latest
    ports:
    - 9180:80
    restart: unless-stopped
  combo_181_l3:
    container_name: combo_181_l3_lighttpd_1.4.72
    image: sebp/lighttpd:1.4.72
    ports:
    - 10180:80
    restart: unless-stopped
version: '3.8'
