services:
  combo_167_l1:
    container_name: combo_167_l1_fastly-simulation
    depends_on:
    - combo_167_l2
    image: nginx:1.25
    ports:
    - 8166:80
    restart: unless-stopped
  combo_167_l2:
    container_name: combo_167_l2_traefik_2.10
    depends_on:
    - combo_167_l3
    image: traefik:2.10
    ports:
    - 9166:80
    restart: unless-stopped
  combo_167_l3:
    container_name: combo_167_l3_openlitespeed_1.7
    image: litespeedtech/openlitespeed:1.7
    ports:
    - 10166:80
    restart: unless-stopped
version: '3.8'
