services:
  combo_003_l1:
    container_name: combo_003_l1_cloudflare-simulation
    depends_on:
    - combo_003_l2
    image: nginx:alpine
    ports:
    - 8002:80
    restart: unless-stopped
  combo_003_l2:
    container_name: combo_003_l2_nginx_1.25
    depends_on:
    - combo_003_l3
    image: nginx:1.25
    ports:
    - 9002:80
    restart: unless-stopped
  combo_003_l3:
    container_name: combo_003_l3_tomcat_10.1
    image: tomcat:10.1
    ports:
    - 10002:80
    restart: unless-stopped
version: '3.8'
