services:
  combo_206_l1:
    container_name: combo_206_l1_cloudflare-simulation
    depends_on:
    - combo_206_l2
    image: nginx:alpine
    ports:
    - 8205:80
    restart: unless-stopped
  combo_206_l2:
    container_name: combo_206_l2_nginx_1.26
    depends_on:
    - combo_206_l3
    image: nginx:1.26
    ports:
    - 9205:80
    restart: unless-stopped
  combo_206_l3:
    container_name: combo_206_l3_apache_2.4.59
    image: httpd:2.4.59
    ports:
    - 10205:80
    restart: unless-stopped
version: '3.8'
