services:
  combo_130_l1:
    container_name: combo_130_l1_fastly-simulation
    depends_on:
    - combo_130_l2
    image: nginx:1.25
    ports:
    - 8129:80
    restart: unless-stopped
  combo_130_l2:
    container_name: combo_130_l2_nginx_1.24
    depends_on:
    - combo_130_l3
    image: nginx:1.24
    ports:
    - 9129:80
    restart: unless-stopped
  combo_130_l3:
    container_name: combo_130_l3_caddy_2.7
    image: caddy:2.7-alpine
    ports:
    - 10129:80
    restart: unless-stopped
version: '3.8'
