services:
  combo_169_l1:
    container_name: combo_169_l1_fastly-simulation
    depends_on:
    - combo_169_l2
    image: nginx:1.25
    ports:
    - 8168:80
    restart: unless-stopped
  combo_169_l2:
    container_name: combo_169_l2_envoy_1.27
    depends_on:
    - combo_169_l3
    image: envoyproxy/envoy:v1.27-latest
    ports:
    - 9168:80
    restart: unless-stopped
  combo_169_l3:
    container_name: combo_169_l3_apache_2.4.58
    image: httpd:2.4.58
    ports:
    - 10168:80
    restart: unless-stopped
version: '3.8'
