services:
  combo_144_l1:
    container_name: combo_144_l1_fastly-simulation
    depends_on:
    - combo_144_l2
    image: nginx:1.25
    ports:
    - 8143:80
    restart: unless-stopped
  combo_144_l2:
    container_name: combo_144_l2_varnish_7.3
    depends_on:
    - combo_144_l3
    image: varnish:7.3
    ports:
    - 9143:80
    restart: unless-stopped
  combo_144_l3:
    container_name: combo_144_l3_openlitespeed_1.8
    image: litespeedtech/openlitespeed:1.8
    ports:
    - 10143:80
    restart: unless-stopped
version: '3.8'
