services:
  combo_242_l1:
    container_name: combo_242_l1_akamai-simulation
    depends_on:
    - combo_242_l2
    image: nginx:1.24
    ports:
    - 8241:80
    restart: unless-stopped
  combo_242_l2:
    container_name: combo_242_l2_envoy_1.28
    depends_on:
    - combo_242_l3
    image: envoyproxy/envoy:v1.28-latest
    ports:
    - 9241:80
    restart: unless-stopped
  combo_242_l3:
    container_name: combo_242_l3_caddy_2.8
    image: caddy:2.8-alpine
    ports:
    - 10241:80
    restart: unless-stopped
version: '3.8'
