services:
  combo_127_l1:
    container_name: combo_127_l1_fastly-simulation
    depends_on:
    - combo_127_l2
    image: nginx:1.25
    ports:
    - 8126:80
    restart: unless-stopped
  combo_127_l2:
    container_name: combo_127_l2_nginx_1.26
    depends_on:
    - combo_127_l3
    image: nginx:1.26
    ports:
    - 9126:80
    restart: unless-stopped
  combo_127_l3:
    container_name: combo_127_l3_lighttpd_1.4.71
    image: sebp/lighttpd:1.4.71
    ports:
    - 10126:80
    restart: unless-stopped
version: '3.8'
