services:
  combo_140_l1:
    container_name: combo_140_l1_fastly-simulation
    depends_on:
    - combo_140_l2
    image: nginx:1.25
    ports:
    - 8139:80
    restart: unless-stopped
  combo_140_l2:
    container_name: combo_140_l2_varnish_7.3
    depends_on:
    - combo_140_l3
    image: varnish:7.3
    ports:
    - 9139:80
    restart: unless-stopped
  combo_140_l3:
    container_name: combo_140_l3_lighttpd_1.4.71
    image: sebp/lighttpd:1.4.71
    ports:
    - 10139:80
    restart: unless-stopped
version: '3.8'
