services:
  combo_232_l1:
    container_name: combo_232_l1_cloudflare-simulation
    depends_on:
    - combo_232_l2
    image: nginx:alpine
    ports:
    - 8231:80
    restart: unless-stopped
  combo_232_l2:
    container_name: combo_232_l2_varnish_7.4
    depends_on:
    - combo_232_l3
    image: varnish:7.4
    ports:
    - 9231:80
    restart: unless-stopped
  combo_232_l3:
    container_name: combo_232_l3_apache_2.4.59
    image: httpd:2.4.59
    ports:
    - 10231:80
    restart: unless-stopped
version: '3.8'
