services:
  combo_059_l1:
    container_name: combo_059_l1_cloudflare-simulation
    depends_on:
    - combo_059_l2
    image: nginx:alpine
    ports:
    - 8058:80
    restart: unless-stopped
  combo_059_l2:
    container_name: combo_059_l2_envoy_1.27
    depends_on:
    - combo_059_l3
    image: envoyproxy/envoy:v1.27-latest
    ports:
    - 9058:80
    restart: unless-stopped
  combo_059_l3:
    container_name: combo_059_l3_openlitespeed_1.8
    image: litespeedtech/openlitespeed:1.8
    ports:
    - 10058:80
    restart: unless-stopped
version: '3.8'
