services:
  combo_204_l1:
    container_name: combo_204_l1_akamai-simulation
    depends_on:
    - combo_204_l2
    image: nginx:1.24
    ports:
    - 8203:80
    restart: unless-stopped
  combo_204_l2:
    container_name: combo_204_l2_nginx_1.24
    depends_on:
    - combo_204_l3
    image: nginx:1.24
    ports:
    - 9203:80
    restart: unless-stopped
  combo_204_l3:
    container_name: combo_204_l3_lighttpd_1.4.71
    image: sebp/lighttpd:1.4.71
    ports:
    - 10203:80
    restart: unless-stopped
version: '3.8'
