services:
  combo_166_l1:
    container_name: combo_166_l1_fastly-simulation
    depends_on:
    - combo_166_l2
    image: nginx:1.25
    ports:
    - 8165:80
    restart: unless-stopped
  combo_166_l2:
    container_name: combo_166_l2_traefik_2.10
    depends_on:
    - combo_166_l3
    image: traefik:2.10
    ports:
    - 9165:80
    restart: unless-stopped
  combo_166_l3:
    container_name: combo_166_l3_caddy_2.7
    image: caddy:2.7-alpine
    ports:
    - 10165:80
    restart: unless-stopped
version: '3.8'
