services:
  combo_039_l1:
    container_name: combo_039_l1_cloudflare-simulation
    depends_on:
    - combo_039_l2
    image: nginx:alpine
    ports:
    - 8038:80
    restart: unless-stopped
  combo_039_l2:
    container_name: combo_039_l2_traefik_2.10
    depends_on:
    - combo_039_l3
    image: traefik:2.10
    ports:
    - 9038:80
    restart: unless-stopped
  combo_039_l3:
    container_name: combo_039_l3_tomcat_10.1
    image: tomcat:10.1
    ports:
    - 10038:80
    restart: unless-stopped
version: '3.8'
