services:
  combo_126_l1:
    container_name: combo_126_l1_fastly-simulation
    depends_on:
    - combo_126_l2
    image: nginx:1.25
    ports:
    - 8125:80
    restart: unless-stopped
  combo_126_l2:
    container_name: combo_126_l2_nginx_1.25
    depends_on:
    - combo_126_l3
    image: nginx:1.25
    ports:
    - 9125:80
    restart: unless-stopped
  combo_126_l3:
    container_name: combo_126_l3_nginx_1.25
    image: nginx:1.25
    ports:
    - 10125:80
    restart: unless-stopped
version: '3.8'
