# LLM-UnTangle 伺服器配置 - 三層架構（90 組擴增版）
# 目標：L1(1) × L2(1) × L3(9) × 每類10組 = 90 組
# 說明：
# - L1/L2 固定為 Nginx
# - L3 每種技術以「多版本 + 輕配置變體」達到每類 10 組覆蓋
# - 若版本數不足 10，剩餘由 replicate_tag 與輕配置變體補足（於 generate_sets.py 產生）

servers:
  l1_cdns:
    - name: nginx-cdn
      image: nginx:1.25-alpine
      config: cdn_simulation.conf
      description: "Nginx CDN 模擬層，添加快取響應頭"

  l2_proxies:
    - name: nginx-proxy
      versions: ["1.25"]
      image: nginx:{version}-alpine
      ports: [80, 443]
      description: "Nginx 反向代理層"

  l3_servers:
    - name: nginx
      versions: ["1.25", "1.26", "1.25-perl", "1.25-alpine", "1.25-bookworm", "1.26-alpine"]
      image: nginx:{version}
      ports: [80, 443]
      description: "Nginx Web 伺服器"

    - name: apache
      versions: ["2.4.57", "2.4.58", "2.4.57-alpine", "2.4.57-bullseye"]
      image: httpd:{version}
      ports: [80, 443]
      description: "Apache HTTP 伺服器"

    - name: tomcat
      versions: ["10.1", "10.1-jdk17", "11.0", "9.0"]
      image: tomcat:{version}
      ports: [8080, 8443]
      description: "Apache Tomcat 應用伺服器"

    - name: caddy
      versions: ["2.7-alpine", "2.8-alpine", "2.7", "2.8"]
      image: caddy:{version}
      ports: [80, 443, 2019]
      description: "Caddy Web 伺服器"

    - name: openlitespeed
      versions: ["1.7", "1.8"]
      image: litespeedtech/openlitespeed:{version}
      ports: [80, 443, 7080]
      description: "OpenLiteSpeed Web 伺服器"

    - name: varnish
      versions: ["7.3", "7.4", "7.5"]
      image: varnish:{version}
      ports: [80, 6081]
      description: "Varnish HTTP 加速器"

    - name: haproxy
      versions: ["2.8", "2.9", "3.0"]
      image: haproxy:{version}
      ports: [80, 443, 8404]
      description: "HAProxy 負載均衡器"

    - name: squid
      versions: ["5.2", "6.2"]
      image: ubuntu/squid:{version}
      ports: [3128, 80]
      description: "Squid 代理伺服器"

    - name: traefik
      versions: ["v3.0", "v3.1"]
      image: traefik:{version}
      ports: [80, 443, 8080]
      description: "Traefik 反向代理"

combination_rules:
  target_count: 90
  max_combinations: 300
  sampling_strategy: "complete_enumeration_then_balance_by_l3"
  ensure_coverage: true
  min_per_l3: 10  # 每個 L3 至少 10 組
  exclude_servers: ["lighttpd"]

network:
  base_port: 8000
  port_range: 2000
