# LLM-UnTangle 伺服器配置 - 簡化版三層架構 (修正版)
# 組合數 = L1(1) × L2(1) × L3(9) = 9 組
# 注意：已移除 lighttpd 由於實驗中無法正常運作
servers:
  l1_cdns:  # 第一層：CDN (固定 1 個 Nginx)
    - name: nginx-cdn
      image: nginx:1.25-alpine
      config: cdn_simulation.conf
      description: "Nginx CDN 模擬層，添加快取響應頭"
    
  l2_proxies:  # 第二層：Proxy (固定 1 個 Nginx)
    - name: nginx-proxy
      versions: ["1.25"]
      image: nginx:{version}-alpine
      ports: [80, 443]
      description: "Nginx 反向代理層"
      
  l3_servers:  # 第三層：應用伺服器 (9 個伺服器，已移除 lighttpd)
    - name: nginx
      versions: ["1.25"]
      image: nginx:{version}-alpine
      ports: [80, 443]
      description: "Nginx Web 伺服器"
      maintenance_status: "⭐⭐⭐ 活躍"
      test_status: "✅ 實驗測試通過"
      
    - name: apache
      versions: ["2.4.57"]
      image: httpd:{version}
      ports: [80, 443]
      description: "Apache HTTP 伺服器"
      maintenance_status: "⭐⭐⭐ 活躍"
      test_status: "✅ 實驗測試通過"
      
    - name: tomcat  
      versions: ["10.1"]
      image: tomcat:{version}
      ports: [8080, 8443]
      description: "Apache Tomcat 應用伺服器"
      maintenance_status: "⭐⭐⭐ 活躍"
      test_status: "✅ 實驗測試通過"
      
    - name: caddy
      versions: ["2.7"]
      image: caddy:{version}-alpine
      ports: [80, 443, 2019]
      description: "Caddy Web 伺服器"
      maintenance_status: "⭐⭐⭐ 活躍"
      test_status: "✅ 實驗測試通過"
      
    # 移除 lighttpd - 實驗中無法正常運作
    # - name: lighttpd
    #   versions: ["1.4.59"]
    #   image: sebp/lighttpd:{version}
    #   ports: [80]
    #   description: "Lighttpd 輕量級 Web 伺服器"
    #   maintenance_status: "⭐ 第三方"
    #   test_status: "❌ 實驗測試失敗 - 無法正常啟動"
      
    - name: openlitespeed
      versions: ["1.7"]
      image: litespeedtech/openlitespeed:{version}
      ports: [80, 443, 7080]
      description: "OpenLiteSpeed Web 伺服器"
      maintenance_status: "⭐⭐ 維護中"
      test_status: "⚠️ 待測試"
      
    - name: varnish
      versions: ["7.4"]
      image: varnish:{version}
      ports: [80, 6081]
      description: "Varnish HTTP 加速器 (作為後端伺服器)"
      maintenance_status: "⭐⭐⭐ 活躍"
      test_status: "⚠️ 待測試"
      
    - name: haproxy
      versions: ["2.8"]
      image: haproxy:{version}
      ports: [80, 443, 8404]
      description: "HAProxy 負載均衡器 (作為後端伺服器)"
      maintenance_status: "⭐⭐⭐ 活躍"
      test_status: "⚠️ 待測試"
      
    - name: squid
      versions: ["5.2"]
      image: ubuntu/squid:{version}
      ports: [3128, 80]
      description: "Squid 代理伺服器 (作為後端伺服器)"
      maintenance_status: "⭐⭐ 維護中"
      test_status: "⚠️ 待測試"
      
    - name: traefik
      versions: ["3.0"]
      image: traefik:v{version}
      ports: [80, 443, 8080]
      description: "Traefik 反向代理 (作為後端伺服器)"
      maintenance_status: "⭐⭐⭐ 活躍"
      test_status: "⚠️ 待測試"

# 特殊配置  
combination_rules:
  target_count: 9   # 目標組合數量：L1(1) × L2(1) × L3(9) = 9 組
  max_combinations: 9   # 最大理論組合數
  sampling_strategy: "complete_enumeration"  # 完全枚舉所有組合
  ensure_coverage: true  # 確保每種技術都有覆蓋
  exclude_servers: ["lighttpd"]  # 排除有問題的伺服器
  
# 基礎端口配置  
network:
  base_port: 8000  # 起始端口號
  port_range: 15   # 端口範圍 (適應 9 組配置)