# LLM-UnTangle 伺服器配置（论文标准版）
# 定義 9 種伺服器類型：L1(3種) × L2(3種) × L3(3種)
# 符合论文研究设计
servers:
  l1_cdns:  # 第一層：CDN/Front
    - name: nginx_l1
      image: nginx:1.20
      config: nginx_l1.conf
      description: "Nginx 前端服务器（L1层）"
    
    - name: haproxy_l1  
      image: haproxy:2.4
      config: haproxy_l1.cfg
      description: "HAProxy 前端负载均衡器（L1层）"
    
    - name: traefik_l1
      image: traefik:2.5
      config: traefik_l1.yml  
      description: "Traefik 前端代理（L1层）"
    
  l2_proxies:  # 第二層：Proxy/Cache
    - name: varnish
      versions: ["7.0"]
      image: varnish:{version}
      ports: [80, 6081]
      description: "Varnish HTTP 缓存加速器（L2层）"
      
    - name: squid
      versions: ["latest"]
      image: ubuntu/squid:{version}
      ports: [3128, 8080]
      description: "Squid 代理缓存服务器（L2层）"
      
    - name: apache
      versions: ["2.4"]
      image: httpd:{version}  
      ports: [80, 443]
      description: "Apache 反向代理（L2层）"
    
  l3_servers:  # 第三層：App/Origin（论文重点测试层）
    - name: tomcat  
      versions: ["9.0"]
      image: tomcat:{version}
      ports: [8080, 8443]
      description: "Apache Tomcat 应用服务器（Java）"
      
    - name: flask
      versions: ["latest"]
      image: llm-untangle-flask:{version}
      ports: [5000]
      description: "Flask 应用服务器（Python）"
      
    - name: express
      versions: ["latest"]
      image: llm-untangle-express:{version}
      ports: [3000]
      description: "Express 应用服务器（Node.js）"

# 特殊配置  
combination_rules:
  target_count: 280  # 目標組合數量
  max_combinations: 500  # 最大理論組合數
  sampling_strategy: "stratified_random"  # 分層隨機抽樣
  ensure_coverage: true  # 確保每種技術都有覆蓋
  
# 基礎端口配置  
network:
  base_port: 8000  # 起始端口號
  port_range: 1000 # 端口範圍