services:
  ood_013_l1:
    container_name: ood_013_l1_cloudflare-simulation
    depends_on:
    - ood_013_l2
    image: nginx:alpine
    labels:
    - ood=true
    - layer=l1
    - combo_id=ood_013
    ports:
    - 9013:80
    restart: unless-stopped
  ood_013_l2:
    container_name: ood_013_l2_nginx_1.24
    depends_on:
    - ood_013_l3
    image: nginx:1.24
    labels:
    - ood=true
    - layer=l2
    - combo_id=ood_013
    ports:
    - 9014:80
    restart: unless-stopped
  ood_013_l3:
    container_name: ood_013_l3_h2o_http2
    image: lkwg82/h2o-http2-server
    labels:
    - ood=true
    - layer=l3
    - combo_id=ood_013
    ports:
    - 9015:80
    restart: unless-stopped
version: '3.8'
